#HSQL Database Engine 1.8.0.10
#Thu May 21 10:24:44 CEST 2026
hsqldb.cache_file_scale=1
hsqldb.cache_scale=13
hsqldb.cache_size_scale=8
hsqldb.cache_version=1.7.0
hsqldb.compatible_version=1.8.0
hsqldb.default_table_type=cached
hsqldb.lock_file=true
hsqldb.log_size=10
hsqldb.nio_data_file=false
hsqldb.original_version=1.8.0
hsqldb.script_format=0
modified=no
readonly=false
runtime.gc_interval=0
sql.enforce_strict_size=true
version=1.8.0
